CREATE TABLE MASTER_USER_IHSAN (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL
);

CREATE TABLE MASTER_ACCOUNT_IHSAN (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    USER_ID RAW(16),
    BALANCE NUMBER NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES MASTER_USER_IHSAN(ID)
);