create table MASTER_USER (
    ID SERIAL PRIMARY KEY,
    FULL_NAME VARCHAR(100) NOT NULL
);

create table MASTER_ACCOUNT (
    ID SERIAL PRIMARY KEY,
    USER_ID INT,
    BALANCE INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES MASTER_USER(ID)
);