INSERT ALL
INTO MASTER_USER_IHSAN (FULL_NAME) VALUES ('John Doe')
INTO MASTER_USER_IHSAN (FULL_NAME) VALUES ('Jane Smith')
INTO MASTER_USER_IHSAN (FULL_NAME) VALUES ('Alice Johnson')
INTO MASTER_USER_IHSAN (FULL_NAME) VALUES ('Bob Brown')
INTO MASTER_USER_IHSAN (FULL_NAME) VALUES ('Charlie Davis')
SELECT 1 FROM dual;